AWSTemplateFormatVersion: 2010-09-09
Description: aws serverless live video distribution

Parameters:
  AllowedMediaLiveInputCidr:
    Description: Allowed CIDR of MediaLive Input
    Type: String
    Default: 0.0.0.0/0

# TODO: リソース名が適当すぎるので、今後修正
Resources:
  # ------------------------------------------------------------#
  # Media Package
  # ------------------------------------------------------------#
  MediaPackageChannel:
    Type: AWS::MediaPackage::Channel
    Properties:
      Description: 'Test Deploy'
      Id: 'test-channel'
      Tags:
        - Key: 'Name'
          Value: 'aws-serverless-live-video-distribution'
  MediaPackageEndpoint:
    Type: AWS::MediaPackage::OriginEndpoint
    Properties:
      ChannelId: !Ref MediaPackageChannel
      Description: 'Endpoint for HLS packaging'
      HlsPackage:
        PlaylistWindowSeconds: 60
        SegmentDurationSeconds: 6
      Id: 'test-endpoint'
      ManifestName: 'index'
      Origination: 'ALLOW'
      Tags:
        - Key: 'Name'
          Value: 'aws-serverless-live-video-distribution'

  # ------------------------------------------------------------#
  # Media Live
  # ------------------------------------------------------------#
  MediaLiveInput:
    Type: AWS::MediaLive::Input
    Properties:
      Destinations:
        - StreamName: 'test-streamA'
        - StreamName: 'test-streamB'
      InputSecurityGroups:
        - !Ref MediaLiveInputSecurityGroup
      Name: 'test-input'
      Tags:
        Name: 'test-input'
      Type: RTMP_PUSH
  MediaLiveInputSecurityGroup:
    Type: AWS::MediaLive::InputSecurityGroup
    Properties:
      Tags:
        Name: 'test-input-sg'
      WhitelistRules:
        - Cidr: !Ref AllowedMediaLiveInputCidr
  MediaLiveChannel:
    Type: AWS::MediaLive::Channel
    Properties:
      ChannelClass: STANDARD
      Destinations:
        - Id: !Ref MediaPackageChannel
          MediaPackageSettings:
            - ChannelId: !Ref MediaPackageChannel
      EncoderSettings:
        AudioDescriptions:
          - AudioSelectorName: default
            CodecSettings:
              AacSettings:
                Bitrate: 96000
                RawFormat: NONE
                Spec: MPEG4
            AudioTypeControl: FOLLOW_INPUT
            LanguageCodeControl: FOLLOW_INPUT
            Name: audio_3_aac96
        OutputGroups:
          - OutputGroupSettings:
              MediaPackageGroupSettings:
                Destination:
                  DestinationRefId: !Ref MediaPackageChannel
            Outputs:
              - OutputSettings:
                  MediaPackageOutputSettings: {}
                OutputName: '1280_720_1'
                VideoDescriptionName: video_1280_720_1
                AudioDescriptionNames:
                  - audio_3_aac96
        TimecodeConfig:
          Source: SYSTEMCLOCK
        VideoDescriptions:
          - CodecSettings:
              H264Settings:
                AfdSignaling: NONE
                ColorMetadata: INSERT
                AdaptiveQuantization: HIGH
                Bitrate: 1000000
                EntropyEncoding: CABAC
                FlickerAq: ENABLED
                FramerateControl: SPECIFIED
                FramerateNumerator: 30000
                FramerateDenominator: 1001
                GopBReference: ENABLED
                GopClosedCadence: 1
                GopNumBFrames: 3
                GopSize: 60
                GopSizeUnits: FRAMES
                SubgopLength: FIXED
                ScanType: PROGRESSIVE
                Level: H264_LEVEL_4_1
                LookAheadRateControl: HIGH
                NumRefFrames: 1
                ParControl: SPECIFIED
                Profile: HIGH
                RateControlMode: CBR
                Syntax: DEFAULT
                SceneChangeDetect: ENABLED
                SpatialAq: ENABLED
                TemporalAq: ENABLED
                TimecodeInsertion: DISABLED
            Height: 720
            Name: video_1280_720_1
            RespondToAfd: NONE
            Sharpness: 50
            ScalingBehavior: DEFAULT
            Width: 1280
      InputAttachments:
        - InputAttachmentName: 'test-input'
          InputId: !Ref MediaLiveInput
          InputSettings:
            DeblockFilter: DISABLED
            DenoiseFilter: DISABLED
            FilterStrength: 1
            InputFilter: AUTO
            SourceEndBehavior: CONTINUE
      InputSpecification:
        Codec: AVC
        MaximumBitrate: MAX_20_MBPS
        Resolution: HD
      Name: 'test-channel'
      RoleArn: !GetAtt
        - MediaLiveAccessRole
        - Arn
      Tags:
        Name: !Sub 'test-channel'
  # TODO: 不要な権限見直し
  MediaLiveAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - medialive.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess'
      Path: /
      Policies:
        - PolicyName: Sample-MediaLiveCustomPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 'mediastore:ListContainers'
                  - 'mediastore:PutObject'
                  - 'mediastore:GetObject'
                  - 'mediastore:DeleteObject'
                  - 'mediastore:DescribeObject'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'mediaconnect:ManagedDescribeFlow'
                  - 'mediaconnect:ManagedAddOutput'
                  - 'mediaconnect:ManagedRemoveOutput'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'mediapackage:DescribeChannel'
                Resource: '*'
      RoleName: 'Test-MediaLiveAccessRole'
